"""empty message

Revision ID: 28f6419c0602
Revises: 10e2d5ccb744
Create Date: 2014-03-03 15:56:40.816000

"""

# revision identifiers, used by Alembic.
revision = '28f6419c0602'
down_revision = '10e2d5ccb744'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
