"""empty message

Revision ID: 531d7cc71722
Revises: None
Create Date: 2014-03-03 14:15:22.328000

"""

# revision identifiers, used by Alembic.
revision = '531d7cc71722'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
